# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30, verbose_name='Customer name')),
                ('LastName', models.CharField(max_length=30, verbose_name='Customer surname')),
                ('BirthDate', models.DateField(default=b'2018/12/02', verbose_name='Customer birthday')),
                ('RegistrationDate', models.DateField(default=b'2018/12/02', verbose_name='Date registration')),
            ],
            options={
                'ordering': ['-RegistrationDate', 'LastName'],
                'db_table': 'customer',
                'verbose_name': 'Customers',
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100, verbose_name='Product name')),
                ('OrderCreateDate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-ProductName', '-OrderCreateDate'],
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='CustomOder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='createcsv.Order'),
        ),
    ]
